theme: jekyll-theme-cayman
title: A Computational Analysis of Real-World DJ Mixes using Mix-To-Track Subsequence Alignment
description: Taejun Kim, Minsuk Choi, Evan Sacks, Yi-Hsuan Yang, and Juhan Nam</br>International Society for Music Information Retrieval Conference (ISMIR), 2020
